export const Colors = {
  bgApp:        '#F0F2FF',
  bgCard:       '#FFFFFF',
  primary:      '#6C2BD9',
  primaryDark:  '#5B21B6',
  primaryLight: '#EDE9FF',
  accent:       '#22C55E',
  accentLight:  '#DCFCE7',
  textPrimary:  '#0D0D0D',
  textSecondary:'#374151',
  textMuted:    '#6B7280',
  border:       '#E5E7EB',
  borderLight:  '#F3F4F6',
  white:        '#FFFFFF',
  correct:      '#22C55E',
  wrong:        '#EF4444',
  warning:      '#F59E0B',
  optionA:      '#EDE9FF',
  optionB:      '#EDE9FF',
  optionC:      '#EDE9FF',
  optionD:      '#EDE9FF',
  shadow:       '#6C2BD9',
};
